# SELECT I.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, ROUND(AVG(REVIEW_SCORE),2) AS SCORE
# FROM REST_INFO AS I JOIN REST_REVIEW AS R
# ON I.REST_ID = R.REST_ID
# WHERE ADDRESS LIKE '%서울%'
# GROUP BY I.REST_ID
# ORDER BY  SCORE DESC,FAVORITES DESC;
SELECT RI.REST_ID
     , REST_NAME
     , FOOD_TYPE
     , FAVORITES
     , ADDRESS
     , ROUND(AVG(RR.REVIEW_SCORE),2) AS SCORE
FROM REST_INFO AS RI
INNER JOIN REST_REVIEW AS RR 
        ON RI.REST_ID = RR.REST_ID
WHERE ADDRESS LIKE "서울%"
GROUP BY RR.REST_ID
ORDER BY SCORE DESC
       , FAVORITES DESC;